import React, { useState } from 'react';
import { AIResponseData, UserProfile } from '../types';
import Logo from './Logo';

interface RoadmapDisplayProps {
  data: AIResponseData;
  user: UserProfile;
  onReset: () => void;
}

const RoadmapDisplay: React.FC<RoadmapDisplayProps> = ({ data, user, onReset }) => {
  const [rating, setRating] = useState<number | null>(null);

  const handleDownload = () => {
    const content = `
AI-LIFE DECISION SIMULATOR - PERSONALIZED ROADMAP
------------------------------------------------
Name: ${user.name}
Goal: ${user.goal}

MOTIVATIONAL QUOTE:
"${data.motivationalQuote}"

CAREER SUMMARY:
${data.careerSummary}

------------------------------------------------
STEP-BY-STEP ROADMAP:
${data.roadmap.map((step, idx) => `
${idx + 1}. ${step.stepName}
   ${step.description}
   Resources:
   ${step.resources.map(r => `   - ${r.title}: ${r.url}`).join('\n')}
`).join('\n')}

------------------------------------------------
WEEKLY SCHEDULE:
${data.weeklySchedule.map(day => `
${day.day} (${day.focus}):
${day.activities.map(a => ` - ${a}`).join('\n')}
`).join('\n')}

------------------------------------------------
Generated by AI-Life Decision Simulator
Disclaimer: AI generated advice. Verify with professionals.
`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${user.name.replace(/\s+/g, '_')}_Career_Roadmap.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-[#0f172a] p-4 md:p-8">
      <div className="max-w-6xl mx-auto space-y-8">
        
        {/* Header */}
        <header className="flex flex-col md:flex-row justify-between items-center bg-slate-900/80 p-6 rounded-2xl border border-slate-700 shadow-lg backdrop-blur gap-4">
          <div className="flex items-center gap-4">
            <Logo size="sm" />
            <div>
              <h1 className="text-2xl font-bold text-white">Hello, {user.name}</h1>
              <p className="text-slate-400">Here is your strategy to become a {user.goal}</p>
            </div>
          </div>
          <div className="flex flex-wrap justify-center gap-3">
             <button onClick={handleDownload} className="px-6 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-full font-semibold transition-all flex items-center gap-2 shadow-lg shadow-blue-900/20">
              <span>📥</span> Download Plan
            </button>
            <button onClick={onReset} className="px-6 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-full font-semibold transition-all">
              New Simulation
            </button>
          </div>
        </header>

        {/* Motivational Quote */}
        <div className="bg-gradient-to-r from-purple-900/40 to-blue-900/40 border border-purple-500/30 p-8 rounded-2xl text-center relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-yellow-400 to-transparent"></div>
          <p className="text-2xl md:text-3xl font-serif italic text-yellow-100">"{data.motivationalQuote}"</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Main Roadmap */}
          <div className="lg:col-span-2 space-y-6">
            <div className="flex justify-between items-center">
                <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                <span className="text-blue-400">🗺️</span> Strategic Roadmap
                </h2>
                <span className="text-xs text-slate-500 border border-slate-700 rounded-full px-3 py-1">AI Generated</span>
            </div>
            
            <div className="space-y-6 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-slate-300 before:to-transparent">
              {data.roadmap.map((step, index) => (
                <div key={index} className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
                  <div className="flex items-center justify-center w-10 h-10 rounded-full border border-slate-700 bg-slate-900 group-hover:bg-blue-600 text-slate-300 group-hover:text-white shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 z-10 transition-colors">
                    {index + 1}
                  </div>
                  <div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] bg-slate-800 p-6 rounded-xl border border-slate-700 shadow-lg hover:shadow-blue-900/20 transition-all">
                    <h3 className="font-bold text-lg text-blue-300 mb-2">{step.stepName}</h3>
                    <p className="text-slate-300 mb-4 text-sm leading-relaxed">{step.description}</p>
                    {step.resources.length > 0 && (
                      <div className="bg-slate-900/50 p-3 rounded-lg border border-slate-700/50">
                        <p className="text-xs font-semibold text-slate-500 uppercase mb-2">Recommended Resources</p>
                        <div className="flex flex-wrap gap-2">
                          {step.resources.map((res, i) => (
                            <a 
                              key={i} 
                              href={res.url} 
                              target="_blank" 
                              rel="noopener noreferrer"
                              className="text-xs bg-blue-900/30 text-blue-300 border border-blue-800 px-3 py-1 rounded-full hover:bg-blue-600 hover:text-white transition-all flex items-center gap-1 group/link"
                            >
                              🔗 {res.title}
                              <span className="opacity-0 group-hover/link:opacity-100 transition-opacity">↗</span>
                            </a>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Sidebar: Monetization & Schedule */}
          <div className="space-y-8">
            
            {/* MONETIZATION: Mentorship Booking */}
            <div className="bg-gradient-to-br from-yellow-500/10 to-orange-500/10 rounded-2xl p-6 border border-yellow-500/30 text-center relative overflow-hidden group">
                <div className="absolute top-0 right-0 p-2 opacity-10 group-hover:opacity-20 transition-opacity">
                    <Logo size="sm" />
                </div>
                <h3 className="text-xl font-bold text-yellow-400 mb-2">Need Personal Guidance?</h3>
                <p className="text-sm text-slate-300 mb-4">
                    Get a 1:1 session with expert career counselors to refine your plan.
                </p>
                <button className="w-full py-3 bg-gradient-to-r from-yellow-600 to-orange-600 hover:from-yellow-500 hover:to-orange-500 text-white font-bold rounded-lg shadow-lg transform transition-all active:scale-95">
                    Book Mentorship Call (₹499)
                </button>
                <p className="text-[10px] text-slate-500 mt-2">Limited slots available for this week.</p>
            </div>

            {/* Weekly Schedule */}
            <div className="bg-slate-800 rounded-2xl p-6 border border-slate-700">
              <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                <span className="text-green-400">📅</span> Weekly Routine
              </h2>
              <div className="space-y-4">
                {data.weeklySchedule.map((day, idx) => (
                  <div key={idx} className="border-b border-slate-700 last:border-0 pb-3 last:pb-0">
                    <div className="flex justify-between items-center mb-1">
                      <span className="font-bold text-slate-200">{day.day}</span>
                      <span className="text-[10px] bg-slate-700 px-2 py-0.5 rounded text-slate-300 uppercase tracking-wider">{day.focus}</span>
                    </div>
                    <ul className="text-sm text-slate-400 list-disc list-inside">
                      {day.activities.slice(0, 2).map((act, i) => (
                        <li key={i} className="truncate">{act}</li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            </div>

            {/* Rating System */}
            <div className="bg-slate-800 rounded-2xl p-6 border border-slate-700 text-center">
              <h3 className="text-white font-semibold mb-3">Rate this Roadmap</h3>
              <div className="flex justify-center gap-2 mb-2">
                {[1, 2, 3, 4, 5].map((star) => (
                  <button
                    key={star}
                    onClick={() => setRating(star)}
                    className={`text-2xl transition-transform hover:scale-125 ${rating && star <= rating ? 'text-yellow-400' : 'text-slate-600'}`}
                  >
                    ★
                  </button>
                ))}
              </div>
              <p className="text-xs text-slate-500">
                {rating ? "Thank you! We are learning." : "Help AI improve accuracy"}
              </p>
            </div>

             {/* Footer with Safety Disclaimer */}
             <div className="mt-8 pt-8 border-t border-slate-800 text-center space-y-2">
               <p className="text-xs text-slate-500">
                 <strong>Disclaimer:</strong> This roadmap is generated by AI for educational guidance. 
                 Please verify important career decisions with professional counselors.
               </p>
               <p className="text-[10px] text-slate-600 font-tech">
                 POWERED BY AI-LIFE SIMULATOR
               </p>
             </div>

          </div>
        </div>
      </div>
    </div>
  );
};

export default RoadmapDisplay;